// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5QfZlMstdDyIpvs7dzWaYoyUJs2Jh1kg',
    appId: '1:505989667991:android:5eca485d0dd826dc155dd2',
    messagingSenderId: '505989667991',
    projectId: 'dropoff-71f5f',
    databaseURL: 'https://dropoff-71f5f-default-rtdb.firebaseio.com',
    storageBucket: 'dropoff-71f5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7C_yJWfrHiaaf4qdvYgOqCkE0Jw8sU40',
    appId: '1:505989667991:ios:f13733a2918e3577155dd2',
    messagingSenderId: '505989667991',
    projectId: 'dropoff-71f5f',
    databaseURL: 'https://dropoff-71f5f-default-rtdb.firebaseio.com',
    storageBucket: 'dropoff-71f5f.appspot.com',
    iosBundleId: 'com.example.dropoff',
  );
}
